### ISSUE TITLE
Flexible Classroom doc update: changes in the release notes

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#1226]
Hi team,

Could you help update the release notes from v2.7.x to v2.8.13? The changes are as follows:

- Combine the v2.8.10, v2.8.11, v2.8.12, and v2.8.13 as one release. This means, the release notes page only has v2.8.13, v2.8.0 and the earlier release versions. The Improvements section lists the improvements made in v2.8.10, v2.8.11, v2.8.12, and v2.8.13, the same to the Issues Fixed section.

- Removes the v2.7.x section title, and add an intro sentence before the beginning of the v2.7.x part: "Please note v2.8.0 incorporated the following new features, improvements, and issue fixed in v2.7.x that was not officially release:". You can refer to the screenshots for preview the changes.
   ![release-notes-changes](https://user-images.githubusercontent.com/45590614/223031836-c7cf89dd-9222-40aa-83a5-8a212fd94a4a.png)

Background: This request was raised by Kyle, product manager of Flexible Classroom. He thinks that because v2.8.10, v2.8.11, v2.8.12, and v2.7.x were not released officially outside China due to product strategies, users might be confused if they see the release notes.  

Feel free to let Kyle (qianfen@agora.io) or me know if any question.

**Comment by KyleQian007** [comment]
Dear, any update about this ticket?

**Comment by billy-the-fish** [comment]
@atovpeko, can you handle this please. 

@KyleQian007, I would much prefer to roll the 2.7 changes into 2.8. To explain, saying: "This happened in something you never had" is a bit like saying "did you see the invisible man". This approach is more confusing than anything else.

**Comment by atovpeko** [comment]
@pmmgithub @KyleQian007 a few clarifications, please:
1. [v2.8.13](https://docs.agora.io/en/flexible-classroom/reference/release-notes?platform=electron#v2813) is the latest release for Electron and Web. For iOS and Android, it's [v2.8.11](https://docs.agora.io/en/flexible-classroom/reference/release-notes?platform=android#v2811). What's the approach for Android/iOS? Have 2.8.10 and 2.8.11 combined under 2.8.11 as latest? Or do we need to add a few releases there so that latest combined is 2.8.13? (In which case I'll need input from you). 
2. We already had [the 2.8.0 release note introducing UI builder](https://docs.agora.io/en/flexible-classroom/reference/release-notes?platform=android#new-features) without specifying anything about it not being based on that same version. Are you sure we need to specify the limitations now? If so, I guess I can add a note there saying that only features from earlier versions and those combined from 2.7.0 are available in it. In this case, it will be good to specify whenever the UI builder is upgraded to be based on a later version in subsequent release notes for clarity.

**Comment by pmmgithub** [comment]
Hi Anastasia @atovpeko , 
1. v2.8.12 and v2.8.13 only impact web/electron platforms, and Android and iOS doesn't have any change in these versions. Can we combine v2.8.10, v2.8.11, v2.8.12, and v2.8.13 as latest version (v2.8.13) for web/electron, and combine v2.8.10 and v2.8.11 as latest version (v2.8.11) for Android/iOS?
2. Do you mean we can add a note to list the features not applicable to ui builder for now, and update or remove the note when we upgrade the ui builder base to a later version in which these limitations don't exist? If my understanding is correct, we agree on this approach.

**Comment by pmmgithub** [comment]
Thanks for your explanation @atovpeko . I got your points. I think we can take this approach.
