### ISSUE TITLE
Missing Information in "Tip:" Block for Agora API

### ISSUE THREAD

**Issue by mystify123** [AgoraIO/Docs-Source#1240]
I am writing to bring to your attention a missing information issue in the "Tip:" block for one of Agora's APIs, specifically the IRTCEngine class for iOS. 

https://api-ref.agora.io/en/video-sdk/ios/4.x/API/class_irtcengine.html#ariaid-title108

See : https://ibb.co/rc47JGF

**Comment by billy-the-fish** [comment]
Can you give me the tag this is on please.

**Comment by Cilla-luodan** [comment]
The original tag is [v4.1.1-native](https://github.com/AgoraIO/agora_doc_source/releases/tag/v4.1.1-native), but we've submitted bugfix release issues since then. I'm not sure if you've used the latest tag for publishing.
In my opinion, this could be a rendering issue, so please check the rendering logic.

**Comment by atovpeko** [comment]
This document is now generated from source, so looks different. @mystify please feel free to open a new ticket if there are still issues. Thank you!
