### ISSUE TITLE
NCS is in the console

### ISSUE THREAD

**Issue by frank005** [AgoraIO/Docs-Source#1280]
Please remove the section that says contact support for NCS, it is in the console now and does not need support to enable.
https://docs.agora.io/en/cloud-recording/develop/integration-best-practices#monitor-service-status-during-a-recording

**Comment by billy-the-fish** [comment]
Can you double check the console setup section as well please.

**Comment by frank005** [comment]
It is correct although some of the names changed

**Comment by saudsami** [comment]
I couldn't find the option to enable the redundant message notification function in the console. Can you please clarify if it is enabled through the console or if it is enabled by default?
![Capture](https://user-images.githubusercontent.com/65331551/226835603-3aae89a5-e52d-41fc-83e5-04ed21d26108.PNG)

**Comment by frank005** [comment]
Not sure if this will go through but redundant messages isn’t available in the console

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by saudsami** [comment]
The paragraph says:
*Agora recommends that you contact [support@agora.io](mailto:support@agora.io) to enable the message notification function, which doubles the received notifications and reduces the probability of message loss*

Given the context, I think it should read "redundant message notification function"  instead of "message notification function". If that is correct, then contacting support for enabling this feature should stay, right?
