### ISSUE TITLE
Migrate signalling docs to the new repo

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#144]
Business case - developers need to easily implement RTM
Fix version - hard release
Subject Matter Expert - @billy-the-fish 
Reviewer - 
Scope - migrate  all docs from https://gitlab.com/agora-documentation/documentation-source/-/tree/milestone-clean-up-migrated-markdown/real-time-messaging to https://github.com/AgoraIO/Docs-Source/tree/main/signalling
Acceptance criteria - developers must be able to easily implement audio and voice effects functionality for electron
Milestone branch - https://github.com/AgoraIO/Docs-Source/issues/140

**Comment by dengyaxi** [comment]
@billy-the-fish Just for your information, the signaling server-side doc has been migrated to mdx: #198. The pull request will be merged to the `main` branch this week.

For the links to work properly, we have changed the folder name from `signalling` to `signaling`, because this is what we get from the landing page
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/73678648/185863408-032694a9-9949-4c40-adf0-6415795fe247.png">

So you might need a global replace across the signaling docs to be migrated from GitLab

**Comment by billy-the-fish** [comment]
Hi @dengyaxi, maybe we should close this ticket?
