### ISSUE TITLE
Media inject vs. Media pull

### ISSUE THREAD

**Issue by xiaov8** [AgoraIO/Docs-Source#297]
while the product name was changed to Media pull, the content is still referring to the product as media inject.  Please check throughout the documents.

**Comment by dengyaxi** [comment]
@billy-the-fish Thanks for cleaning up the product overview page. For the Media Pull docset, a few more things need a fix:

- "Enable Media Push" --> "Enable Media Pull"
- "Media Inject RESTful API" --> "Media Pull RESTful API"
- The `shared/media-inject` folder should be renamed, so as links to this folder. Because all writers are going to collaborate on the same repo, we'd better keep consistency and minimize confusion

**Comment by kelzr** [comment]
@billy-the-fish Please hide or offline all the media inject (client side only) doc per the product sunset plan from our PM: Mei Rongjun (Roger).

**Comment by yamasite** [comment]
@ghuddy Please also be noted

**Comment by billy-the-fish** [comment]
@dengyaxi, I've done the naming update because I am a very nice and helpful chap. I'm afraid this merge and updates are with you. Can you assign the ticket to yourself please.

**Comment by dengyaxi** [comment]
@billy-the-fish Thank you for filling in when we were not available to help due to time differences. I thought you wanted to take care of the name updates thoroughly.

Anyway, now we get things clear. I will continue with the remaining naming clean-up.

**Comment by dengyaxi** [comment]
All clean-up is done. Will merge the changes before the second internal test
