### ISSUE TITLE
[Cleanup - Signaling] Disordered display due to current reuse logic

### ISSUE THREAD

**Issue by jinyuagora** [AgoraIO/Docs-Source#412]
The disordered display issues due to the reuse logic occur when a product supports several platforms; however, a topic covers only some of them. This issue occurs on the following Unity pages:
**Call invitation**
**Geofencing**

Take **Call invitation** as an example:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/101544891/191702703-74e2a5ea-0c58-45d4-b3fd-a9e4d9f141f6.png">

**Comment by jinyuagora** [comment]
A workaround for this case is to create a file for this platform with something like "This feature does not support xxx" in it.
In a long run, you'd better fix this bug in reuse logic.

**Comment by billy-the-fish** [comment]
So, the reuse logic works fine, the problem is that there is no implementation for Unity. I agree that the best short term workaround is to put conditional text saying "no implementation" rather than no functionality. 

\<PlatformWrapper platform="unity">
This functionality is not implimented for Unity.
\</PlatformWrapper>
\<PlatformWrapper notAllowed="unity">
...
the page source
...

\</PlatformWrapper>



A small linguistic note for you. Saying "a good solution would be ..." is good English, the term "you better" is a threat; it implies a consequence. "You better do this or things will go badly for you".

**Comment by billy-the-fish** [comment]
In PR: https://github.com/AgoraIO/Docs-Source/pull/433

**Comment by jinyuagora** [comment]
A small linguistic note for you. implimented --> implemented.

The problem is not that there is no implementation for Unity. This is just a fact instead of a problem - a feature / solution that supports only some of the platforms is a common case for Agora's products.  The reuse logic and everything of the new site should be fact-based undoubtedly.

Everyone who raises issues and exposes risks before the hard launch has a good will. Nobody's gonna threat you before all these issues finally compromise Agora's external image. :)
