### ISSUE TITLE
Cloud proxy keywords

### ISSUE THREAD

**Issue by embkim** [AgoraIO/Docs-Source#738]
Hi - can you add "cloud proxy" to the page copy and/or titles so that [this page](https://docs.agora.io/en/video-calling/develop/media-stream-encryption) comes up better in search? Thank you.

**Comment by atovpeko** [comment]
@embkim to clarify just in case - [Secure channel encryption page](https://docs.agora.io/en/video-calling/develop/media-stream-encryption)? Or maybe [Restricted network connection](https://docs.agora.io/en/video-calling/develop/cloud-proxy)?

**Comment by embkim** [comment]
@atovpeko you are right! I meant the Restricted network connection page. Thanks for catching that!

**Comment by atovpeko** [comment]
@embkim the page already has: 
- 22 mentions of "cloud proxy" in the main body
- an embedded image file called "cloud-proxy.png"
- the URL ending in "cloud-proxy"
- the meta description containing this phrase

So I only added a few mentions in the copy and headers (which might already be too much for @billy-the-fish since these headers are supposed to be consistent across products). I'd say we did as much as possible on main keyword optimization here, add some more and Google might penalize the page for spamming. Maybe some backlinking could help?

**Comment by embkim** [comment]
Hi @atovpeko sorry for the confusion. I do see that I said "page copy and/or titles" but it's really more important for it to appear in a header since our search is prioritizing headers. (I was referring to our site search not Google search). Thanks!

**Comment by atovpeko** [comment]
Done
