### ISSUE TITLE
[RTC 3.x only] Content Update for Raw Video Data

### ISSUE THREAD

**Issue by kelzr** [AgoraIO/Docs-Source#853]
Based on R&D feedback (https://jira.agoralab.co/browse/CSD-51019), please add the following notes to the raw video data guide, as detailed in the EN section of this confluence page: https://confluence.agoralab.co/pages/viewpage.action?pageId=1132201493.

**Comment by billy-the-fish** [comment]
The content is: 

When you use the SDK v3.0.1 or later, note the following:

The SDK no longer guarantees that callback functions in IVideoFrameObserver are reported in the same thread. The SDK only guarantees the sequence of these callbacks.
If you are using OpenGL to perform image enhancement on the raw video data, you need to actively switch the OpenGL context in the callback function in IVideoFrameObserver to adapt to a multi-threaded scenario; otherwise, the image enhancement cannot work..

Again, please use the milestone-29-video-sdk-for-web-4.15.0 in docs-source so we can put this out with Video Calling for Web 3.15.0.

**Comment by kelzr** [comment]
More information to share with you: This update is only for RTC 3.x SDK for Android, iOS, macOS, and Windows. @nirm2009
